FROM mcr.microsoft.com/dotnet/sdk:6.0.403-jammy-amd64 AS build

ENV PATH="${PATH}:/root/.dotnet/tools"

WORKDIR /usr/src/app

RUN dotnet --info

RUN dotnet tool install --global dotnet-ef

# Copy csproj and restore as distinct layers
COPY src/backend.csproj src/backend.csproj

RUN dotnet restore src

RUN dotnet dev-certs https --trust

COPY src src

WORKDIR /usr/src/app/src

RUN touch db.sqlite

CMD [ "dotnet", "ef", "database", "update" ]
