name: Build and Publish Production Docker Images

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  frontend:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Define services
        run: echo '[{"icon":"61484","fontFamily":"FontAwesomeSolid","fontPackage":"font_awesome_flutter","name":"Catalog","url":"http://maersk-catalog.duckdns.org/"},{"icon":"62069","fontFamily":"FontAwesomeSolid","fontPackage":"font_awesome_flutter","name":"Inbound","url":"http://maersk-inbound.duckdns.org/"},{"icon":"62096","fontFamily":"FontAwesomeSolid","fontPackage":"font_awesome_flutter","name":"Brand Config","url":"http://maersk-config.duckdns.org/"}]' > ./frontend/assets/data/services.local.json

      - name: Give access to design design system
        run: cd frontend/pat && echo ${{ secrets.PAT }} > pat && ./replace_pat.sh

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/dostini/dev-maersk

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./frontend/
          file: ./frontend/Dockerfile.prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd frontend && flyctl deploy --local-only --image ghcr.io/dostini/dev-maersk:main

  backend:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/dostini/dev-maersk-api

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./backend/
          file: ./backend/Dockerfile.prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd backend && flyctl deploy --local-only --image ghcr.io/dostini/dev-maersk-api:main
