name: Build and Publish Development Docker Images

on:
  push:
    branches:
      - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  frontend:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: dostini
          password: ${{ secrets.TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/dostini/maersk-inbound

      - name: Give access to design design system
        run: cd frontend/pat && echo ${{ secrets.PAT }} > pat && ./replace_pat.sh

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./frontend/
          file: ./frontend/Dockerfile.prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: BACKEND_URL=${{ secrets.BACKEND_URL_DEV }}

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd frontend && cp fly.dev.toml fly.toml && flyctl deploy --local-only --image ghcr.io/dostini/maersk-inbound:develop

  backend:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: dostini
          password: ${{ secrets.TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/dostini/maersk-inbound-api

      - name: Build appsettings config file
        run: echo '${{secrets.APPSETTINGS_DEV}}' >> backend/src/appsettings.local.json
        shell: bash

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./backend/
          file: ./backend/Dockerfile.prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd backend && cp fly.dev.toml fly.toml && flyctl deploy --local-only --image ghcr.io/dostini/maersk-inbound-api:develop
