// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221120050155_AddVariants")]
    partial class AddVariants
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("backend.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Puma"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Levi's"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Havaianas"
                        });
                });

            modelBuilder.Entity("backend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Season")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubFamily")
                        .HasColumnType("TEXT");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Family = "Shoes",
                            Name = "Air Force",
                            Supplier = "Nike Man.",
                            Type = "Clothing"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Family = "Shoes",
                            Name = "Air Jordan 2 Low",
                            Supplier = "Nike Man.",
                            Type = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            Family = "Shoes",
                            Name = "Maersk x Puma suede shoes",
                            Supplier = "Puma Man.",
                            Type = "Clothing"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 3,
                            Family = "Jackets",
                            Name = "Levi's Gold Tab Lined Worker Jacket",
                            Supplier = "Levi's Man.",
                            Type = "Clothing"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 4,
                            Family = "Flip-Flops",
                            Name = "Havaianas Brasil Logo",
                            Supplier = "Havaianas Man.",
                            Type = "Clothing"
                        });
                });

            modelBuilder.Entity("backend.Models.Variant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgeGroup")
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Composition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Dangerous")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Depth")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.Property<string>("Fabric")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Height")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.Property<string>("Hscode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PackingCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrePackedItem")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PriceRetail")
                        .HasColumnType("REAL");

                    b.Property<double?>("PriceWholesale")
                        .HasColumnType("REAL");

                    b.Property<int?>("ProductId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UN")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VariantDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Weight")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.Property<double?>("Width")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Variants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "5714326008476",
                            Composition = "100% Leather",
                            Country = "US",
                            Currency = "USD",
                            Depth = 25.0,
                            Height = 6.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 1,
                            SKU = "tra/nik/whi/lea",
                            VariantDescription = "White version",
                            Weight = 0.73999999999999999,
                            Width = 5.0
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "5714326008477",
                            Composition = "100% Leather",
                            Country = "US",
                            Currency = "USD",
                            Depth = 25.0,
                            Height = 6.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 1,
                            SKU = "tra/nik/whi/lea",
                            VariantDescription = "Black version",
                            Weight = 0.73999999999999999,
                            Width = 5.0
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "5714326008478",
                            Composition = "100% Leather",
                            Country = "US",
                            Currency = "USD",
                            Depth = 25.0,
                            Height = 6.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 1,
                            SKU = "tra/nik/whi/lea",
                            VariantDescription = "Brown version",
                            Weight = 0.73999999999999999,
                            Width = 5.0
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "5714326008476",
                            Composition = "100% Leather",
                            Country = "PT",
                            Currency = "EUR",
                            Depth = 25.0,
                            Height = 6.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 1,
                            SKU = "tra/nik/whi/lea",
                            VariantDescription = "White version",
                            Weight = 0.73999999999999999,
                            Width = 5.0
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "5714326008477",
                            Composition = "100% Leather",
                            Country = "PT",
                            Currency = "EUR",
                            Depth = 25.0,
                            Height = 6.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 1,
                            SKU = "tra/nik/whi/lea",
                            VariantDescription = "Black version",
                            Weight = 0.73999999999999999,
                            Width = 5.0
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "5714326008478",
                            Composition = "100% Leather",
                            Country = "PT",
                            Currency = "EUR",
                            Depth = 25.0,
                            Height = 6.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 1,
                            SKU = "tra/nik/whi/lea",
                            VariantDescription = "Brown version",
                            Weight = 0.73999999999999999,
                            Width = 5.0
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "5214426038376",
                            Composition = "100% Leather",
                            Country = "PT",
                            Currency = "EUR",
                            Depth = 30.0,
                            Height = 5.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 2,
                            SKU = "DV7129-222",
                            VariantDescription = "White version",
                            Weight = 0.80000000000000004,
                            Width = 4.0
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "5214426038376",
                            Composition = "100% Leather",
                            Country = "PT",
                            Currency = "EUR",
                            Depth = 30.0,
                            Height = 5.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 2,
                            SKU = "DV7129-222",
                            VariantDescription = "Black version",
                            Weight = 0.80000000000000004,
                            Width = 4.0
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "5214426038376",
                            Composition = "100% Leather",
                            Country = "PT",
                            Currency = "EUR",
                            Depth = 30.0,
                            Height = 5.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 2,
                            SKU = "DV7129-222",
                            VariantDescription = "Brown version",
                            Weight = 0.80000000000000004,
                            Width = 4.0
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "5214426038376",
                            Composition = "50% Leather, 50% Cotton",
                            Country = "PT",
                            Currency = "EUR",
                            Depth = 30.0,
                            Height = 5.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 2,
                            SKU = "DV7129-222",
                            VariantDescription = "White version",
                            Weight = 0.80000000000000004,
                            Width = 4.0
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "5214426038376",
                            Composition = "50% Leather, 50% Cotton",
                            Country = "PT",
                            Currency = "EUR",
                            Depth = 30.0,
                            Height = 5.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 2,
                            SKU = "DV7129-222",
                            VariantDescription = "Black version",
                            Weight = 0.80000000000000004,
                            Width = 4.0
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "5214426038376",
                            Composition = "50% Leather, 50% Cotton",
                            Country = "PT",
                            Currency = "EUR",
                            Depth = 30.0,
                            Height = 5.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 2,
                            SKU = "DV7129-222",
                            VariantDescription = "Brown version",
                            Weight = 0.80000000000000004,
                            Width = 4.0
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "5234426937376",
                            Composition = "10% Cotton, 90% Polyamide",
                            Country = "US",
                            Currency = "USD",
                            Depth = 27.0,
                            Height = 4.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 3,
                            SKU = "DV7119-222",
                            VariantDescription = "Blue version",
                            Weight = 0.59999999999999998,
                            Width = 4.0
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "5947420582976",
                            Composition = "100% Cotton",
                            Country = "FR",
                            Currency = "EUR",
                            Depth = 1.0,
                            Height = 10.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 4,
                            SKU = "DV4519-222",
                            VariantDescription = "Blue version",
                            Weight = 0.59999999999999998,
                            Width = 5.0
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "1237493750276",
                            Composition = "100% Rubber",
                            Country = "BZ",
                            Currency = "BRL",
                            Depth = 1.0,
                            Height = 20.0,
                            Hscode = "34631920",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 5,
                            SKU = "DV4519-222",
                            VariantDescription = "Green version",
                            Weight = 0.59999999999999998,
                            Width = 5.0
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "5714326008476",
                            Composition = "100% Pain",
                            Country = "US",
                            Currency = "USD",
                            Depth = 25.0,
                            Height = 6.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 1,
                            SKU = "tra/nik/whi/lea",
                            VariantDescription = "DS version",
                            Weight = 0.73999999999999999,
                            Width = 5.0
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "5714326008477",
                            Composition = "100% Pain",
                            Country = "US",
                            Currency = "USD",
                            Depth = 25.0,
                            Height = 6.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 1,
                            SKU = "tra/nik/whi/lea",
                            VariantDescription = "DS version",
                            Weight = 0.73999999999999999,
                            Width = 5.0
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "5714326008478",
                            Composition = "100% Pain",
                            Country = "US",
                            Currency = "USD",
                            Depth = 25.0,
                            Height = 6.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 1,
                            SKU = "tra/nik/whi/lea",
                            VariantDescription = "DS version",
                            Weight = 0.73999999999999999,
                            Width = 5.0
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "5714326008476",
                            Composition = "100% Pain",
                            Country = "PT",
                            Currency = "EUR",
                            Depth = 25.0,
                            Height = 6.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 1,
                            SKU = "tra/nik/whi/lea",
                            VariantDescription = "DS version",
                            Weight = 0.73999999999999999,
                            Width = 5.0
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "5714326008477",
                            Composition = "100% Pain",
                            Country = "PT",
                            Currency = "EUR",
                            Depth = 25.0,
                            Height = 6.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 1,
                            SKU = "tra/nik/whi/lea",
                            VariantDescription = "DS version",
                            Weight = 0.73999999999999999,
                            Width = 5.0
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "5714326008478",
                            Composition = "100% Pain",
                            Country = "PT",
                            Currency = "EUR",
                            Depth = 25.0,
                            Height = 6.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 1,
                            SKU = "tra/nik/whi/lea",
                            VariantDescription = "DS version",
                            Weight = 0.73999999999999999,
                            Width = 5.0
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "5214426038376",
                            Composition = "100% Pain",
                            Country = "PT",
                            Currency = "EUR",
                            Depth = 30.0,
                            Height = 5.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 2,
                            SKU = "DV7129-222",
                            VariantDescription = "DS version",
                            Weight = 0.80000000000000004,
                            Width = 4.0
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "5214426038376",
                            Composition = "100% Pain",
                            Country = "PT",
                            Currency = "EUR",
                            Depth = 30.0,
                            Height = 5.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 2,
                            SKU = "DV7129-222",
                            VariantDescription = "DS version",
                            Weight = 0.80000000000000004,
                            Width = 4.0
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "5214426038376",
                            Composition = "100% Pain",
                            Country = "PT",
                            Currency = "EUR",
                            Depth = 30.0,
                            Height = 5.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 2,
                            SKU = "DV7129-222",
                            VariantDescription = "DS version",
                            Weight = 0.80000000000000004,
                            Width = 4.0
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "5214426038376",
                            Composition = "100% Pain",
                            Country = "PT",
                            Currency = "EUR",
                            Depth = 30.0,
                            Height = 5.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 2,
                            SKU = "DV7129-222",
                            VariantDescription = "DS version",
                            Weight = 0.80000000000000004,
                            Width = 4.0
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "5214426038376",
                            Composition = "100% Pain",
                            Country = "PT",
                            Currency = "EUR",
                            Depth = 30.0,
                            Height = 5.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 2,
                            SKU = "DV7129-222",
                            VariantDescription = "DS version",
                            Weight = 0.80000000000000004,
                            Width = 4.0
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "5214426038376",
                            Composition = "100% Pain",
                            Country = "PT",
                            Currency = "EUR",
                            Depth = 30.0,
                            Height = 5.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 2,
                            SKU = "DV7129-222",
                            VariantDescription = "DS version",
                            Weight = 0.80000000000000004,
                            Width = 4.0
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "5234426937376",
                            Composition = "100% Pain",
                            Country = "US",
                            Currency = "USD",
                            Depth = 27.0,
                            Height = 4.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 3,
                            SKU = "DV7119-222",
                            VariantDescription = "DS version",
                            Weight = 0.59999999999999998,
                            Width = 4.0
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "5947420582976",
                            Composition = "100% Pain",
                            Country = "FR",
                            Currency = "EUR",
                            Depth = 1.0,
                            Height = 10.0,
                            Hscode = "64031900",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 4,
                            SKU = "DV4519-222",
                            VariantDescription = "DS version",
                            Weight = 0.59999999999999998,
                            Width = 5.0
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "1237493750276",
                            Composition = "100% Pain",
                            Country = "BZ",
                            Currency = "BRL",
                            Depth = 1.0,
                            Height = 20.0,
                            Hscode = "34631920",
                            IsArchived = false,
                            PrePackedItem = "No",
                            ProductId = 5,
                            SKU = "DV4519-222",
                            VariantDescription = "DS version",
                            Weight = 0.59999999999999998,
                            Width = 5.0
                        });
                });

            modelBuilder.Entity("backend.Models.Product", b =>
                {
                    b.HasOne("backend.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("backend.Models.Variant", b =>
                {
                    b.HasOne("backend.Models.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("backend.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("backend.Models.Product", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
